# Generated by Django 3.1.2 on 2021-03-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentrecord',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('RollNo', models.IntegerField()),
                ('Name', models.CharField(max_length=60)),
                ('Maths', models.IntegerField()),
                ('Physics', models.IntegerField()),
                ('Chemistry', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('Percentage', models.FloatField()),
            ],
        ),
    ]
